config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users, :only => [:show]
  
  resources :tweets do
    resources :comments
end

root 'tweets#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base

belongs_to :user
has_many :comments


has_attached_file :image, :styles => { :medium => "200x200>", :large => "1000x1000>" }, :default_url => "/images/:style/missing.png"
validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/




def to_s
body
end

end

app/models/user.rb
class User < ActiveRecord::Base
  
  
  # validates :email, presence: true
  # validates :username, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :tweets

def to_s
username
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) << :username
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) << :username
  end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def create
  @comment = Comment.new(comment_params)
  @comment.author_name = current_user.username
  @comment.tweet_id = params[:tweet_id]

  @comment.save

  redirect_to tweet_path(@comment.tweet)
end

def comment_params
  params.require(:comment).permit(:author_name, :body)
end



end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  respond_to :html

  
  def index
    @tweets = Tweet.order(created_at: :desc).paginate(:page => params[:page], :per_page => 20)
    respond_with(@tweets)   
  end

  def show
    @comment = Comment.new
    @comment.author_name = current_user.username if current_user.present?
    @comment.tweet_id = @tweet.id

    respond_with(@tweet)
  end

  def new
    @tweet = Tweet.new
    respond_with(@tweet)
  end

  def edit
    @comment = Comment.new
    
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)
    @tweet.save
    redirect_to root_path #After creation of Tweet go to Index action, not Show
  end

  def update
    @tweet.update(tweet_params)
    respond_with(@tweet)
  end

  def destroy
    @tweet.destroy
    respond_with(@tweet)
  end

  private
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def tweet_params
      params.require(:tweet).permit(:body, :username, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
@user = User.find(params[:id])
end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/comments/_form.html.erb
<div class="row">
<div class="col-lg-12">
<h3>Post a Comment</h3>

<%= form_for [ @tweet, @comment ] do |f| %>
  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>
</div>
</div>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'TC Twitter', root_path, class: "navbar-brand" %>
        </div>
                  </ul>
          <ul class="nav navbar-nav navbar-right">
<% if user_signed_in? %>
    <li><%= link_to 'New Tweet', new_tweet_path, class: "newtweetbutton" %></li>
    <li><%= link_to 'My Tweets', current_user %></li>
    <li><%= link_to current_user.username, edit_user_registration_path %></li>
    <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
            
<% else %>

    <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>

          
        
        </div>
      </div>
    </nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <% if user_signed_in? %> <!-- Show username in title if user is signed in -->
  <title>TC Twitter - <%= current_user.username %> </title>
  <% else %>
  <title>TC Twitter</title>
  <% end %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>

<%= render 'layouts/menu' %>

<%= yield %>

</body>
</html>

app/views/tweets/_comment.html.erb
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
  <h4><%= comment.author_name %>:</h4>
  <p><%= comment.body %></p>
</div>

app/views/tweets/_form.html.erb
<%= form_for @tweet, :html => { :class => "form-horizontal tweet" } do |f| %>

    <% if @tweet.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @tweet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label " ", :class => 'control-label' %>
    <div class="controls file_field">
      <%= f.file_field :image %>
    </div>
    <div class="controls">
      <%= f.text_area :body, :class => 'form-control', :maxlength => 160 %>
    </div>
    <%= error_span(@tweet[:body]) %>
  </div>

<div class="control-group">
  <%= f.submit nil, :class => 'btn btn-lg btn-primary' %><!-- Render Delete button only on Update action, not New -->
  <% if current_page?(action: 'new') %> 
  <% else %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")), tweet_path(@tweet), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-lg btn-danger' %>
<% end %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            tweets_path, :class => 'btn btn-lg btn-default' %>

<% end %>

app/views/tweets/edit.html.erb
<div class="container app">
<div class="row">
<div class="col-lg-12">
<div class="well">

<%- model_class = Tweet -%>
<div class="page-header">
  <h1 class="text-center">What are you thinking of?</h1>
  <h3 class="text-center">Max. 160 characters</h3>
</div>


<%= render :partial => 'form' %>

<% if @tweet.comments.present? %>
<h3>Comments:</h3>
<%= render partial: 'tweets/comment', collection: @tweet.comments %>
<% end %>
<%= render partial: 'comments/form' if user_signed_in? %>


</div>
</div>
</div>
</div>

app/views/tweets/index.html.erb
<div class="container-fluid app">
<div class="row row-centered">


<% @tweets.each do |tweet| %>
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 well col-centered tweet text-center">


<h5><%= link_to tweet.user, tweet.user %></h5>


<%= link_to image_tag(tweet.image(:medium)), url_for(tweet), class:"img-thumbnail img-responsive" if tweet.image.present? %>



<h3><%= link_to tweet.body, tweet %></h3>

<% if tweet.comments.size==1 %>
<h5 class="commentsonindespage">1 comment</h5>
<% elsif tweet.comments.size>1 %>
<h5 class="commentsonindespage"><%= tweet.comments.size %> comments</h5>
<% end %>
</div>

<% end %>

</div>



<div class="row row-centered pagination-wrapper">
<%= will_paginate @tweets, renderer: BootstrapPagination::Rails %>
</div>


</div>

app/views/tweets/new.html.erb
<div class="container app">
<div class="row">
<div class="col-lg-12">
<div class="well">

<div class="page-header">
  <h1 class="text-center">What are you thinking of?</h1>
  <h3 class="text-center">Max. 160 characters</h3>
</div>
<%= render :partial => 'form' %>

</div>
</div>
</div>
</div>

app/views/tweets/show.html.erb
<div class="container app">
<div class="row">
<div class="col-lg-12">


<div class="well tweet text-center">

<h4><%= link_to @tweet.user, @tweet.user %></h4>
<%= image_tag @tweet.image(:large), class: "img-thumbnail img-responsive" %>
<h1><%= @tweet %></h1>


<% if @tweet.user == current_user %> 

<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_tweet_path(@tweet), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              tweet_path(@tweet),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<% end %>

<div class="row">

<% if @tweet.comments.present? %>
<h3>Comments:</h3>
<%= render partial: 'tweets/comment', collection: @tweet.comments %>
</div>
<% end %>

<%= render partial: 'comments/form' if user_signed_in? %>


</div>


</div>
</div>
</div>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>

    <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:email]) %>
  </div>
  <div class="control-group">
    <%= f.label :encrypted_password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :encrypted_password, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:encrypted_password]) %>
  </div>
  <div class="control-group">
    <%= f.label :reset_password_token, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :reset_password_token, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:reset_password_token]) %>
  </div>
  <div class="control-group">
    <%= f.label :reset_password_sent_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :reset_password_sent_at, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:reset_password_sent_at]) %>
  </div>
  <div class="control-group">
    <%= f.label :remember_created_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :remember_created_at, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:remember_created_at]) %>
  </div>
  <div class="control-group">
    <%= f.label :current_sign_in_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :current_sign_in_at, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:current_sign_in_at]) %>
  </div>
  <div class="control-group">
    <%= f.label :last_sign_in_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_sign_in_at, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:last_sign_in_at]) %>
  </div>
  <div class="control-group">
    <%= f.label :current_sign_in_ip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :current_sign_in_ip, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:current_sign_in_ip]) %>
  </div>
  <div class="control-group">
    <%= f.label :last_sign_in_ip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_sign_in_ip, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:last_sign_in_ip]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            users_path, :class => 'btn btn-default' %>

<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:encrypted_password) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_token) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_sent_at) %></th>
      <th><%= model_class.human_attribute_name(:remember_created_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.encrypted_password %></td>
        <td><%= user.reset_password_token %></td>
        <td><%= user.reset_password_sent_at %></td>
        <td><%= user.remember_created_at %></td>
        <td><%= user.current_sign_in_at %></td>
        <td><%= user.last_sign_in_at %></td>
        <td><%= user.current_sign_in_ip %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<div class="container-fluid app">
<div class="row row-centered">

<div class="jumbotron">
<h1>All Tweets by <%= @user.username %>:</h1>
</div>

<% @user.tweets.order(created_at: :desc).each do |tweet| %>
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 well col-centered tweet text-center">

<%= link_to image_tag(tweet.image(:medium)), url_for(tweet), class:"img-thumbnail img-responsive" if tweet.image.present? %>

<% if tweet.user == current_user %> <!-- If currently logged in user is creator of Tweet, user can go directly to Update action from Index, no need to go to Show -->
<h3><%= link_to tweet.body, edit_tweet_path(tweet) %></h3>
<% else %>
<h3><%= link_to tweet.body, tweet %></h3>
<% end %>

<% if tweet.comments.size==1 %>
<h5 class="commentsonindespage">1 comment</h5>
<% elsif tweet.comments.size>1 %>
<h5 class="commentsonindespage"><%= tweet.comments.size %> comments</h5>
<% end %>

</div>

<% end %>

</div>
</div>